export const GET_INITIAL_CITY_SUCCESS = 'GET_INITIAL_CITY_SUCCESS';
export const GET_INITIAL_WEATHER_SUCCESS = 'GET_INITIAL_WEATHER_SUCCESS';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';

export const GET_CITY_NAME = 'GET_CITY_NAME';
export const TOGGLE_UNIT = 'TOGGLE_UNIT';
export const UPDATE_UNITS = 'UPDATE_UNITS';
export const CLEAN_INPUT = 'CLEAN_INPUT';
