export const GET_INITIAL_CITY_SUCCESS = 'GET_INITIAL_CITY_SUCCESS';
export const GET_INITIAL_WEATHER_SUCCESS = 'GET_INITIAL_WEATHER_SUCCESS';
export const GET_COMING_WEATHER_SUCCESS = 'GET_COMING_WEATHER_SUCCESS';
